/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DebugUmbracoRouteImport } from './routes/_debug.umbraco'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugUmbracoRoute = DebugUmbracoRouteImport.update({
  id: '/_debug/umbraco',
  path: '/umbraco',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/umbraco': typeof DebugUmbracoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/umbraco': typeof DebugUmbracoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_debug/umbraco': typeof DebugUmbracoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/umbraco'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/umbraco'
  id: '__root__' | '/' | '/_debug/umbraco'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DebugUmbracoRoute: typeof DebugUmbracoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_debug/umbraco': {
      id: '/_debug/umbraco'
      path: '/umbraco'
      fullPath: '/umbraco'
      preLoaderRoute: typeof DebugUmbracoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DebugUmbracoRoute: DebugUmbracoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
